// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ClientApp.Models
{
    public partial class BookChapter
    {
        private string _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ID
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private int? _number;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Number
        {
            get { return this._number; }
            set { this._number = value; }
        }
        
        private int? _pages;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Pages
        {
            get { return this._pages; }
            set { this._pages = value; }
        }
        
        private string _title;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Title
        {
            get { return this._title; }
            set { this._title = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the BookChapter class.
        /// </summary>
        public BookChapter()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type BookChapter
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.ID != null)
            {
                outputObject["id"] = this.ID;
            }
            if (this.Number != null)
            {
                outputObject["number"] = this.Number.Value;
            }
            if (this.Pages != null)
            {
                outputObject["pages"] = this.Pages.Value;
            }
            if (this.Title != null)
            {
                outputObject["title"] = this.Title;
            }
            return outputObject;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken idValue = inputObject["id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.ID = ((string)idValue);
                }
                JToken numberValue = inputObject["number"];
                if (numberValue != null && numberValue.Type != JTokenType.Null)
                {
                    this.Number = ((int)numberValue);
                }
                JToken pagesValue = inputObject["pages"];
                if (pagesValue != null && pagesValue.Type != JTokenType.Null)
                {
                    this.Pages = ((int)pagesValue);
                }
                JToken titleValue = inputObject["title"];
                if (titleValue != null && titleValue.Type != JTokenType.Null)
                {
                    this.Title = ((string)titleValue);
                }
            }
        }
    }
}
