// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ClientApp.Models;
using Newtonsoft.Json.Linq;

namespace ClientApp.Models
{
    public static partial class BookChapterCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<BookChapter> DeserializeJson(JToken inputObject)
        {
            IList<BookChapter> deserializedObject = new List<BookChapter>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                BookChapter bookChapter = new BookChapter();
                bookChapter.DeserializeJson(iListValue);
                deserializedObject.Add(bookChapter);
            }
            return deserializedObject;
        }
    }
}
