//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 9/15/2016 12:21:03 PM
namespace ClientApp.ServiceReference1
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "TheOldWebAPIService.Models", "ClientApp.ServiceReference1");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ClientApp.ServiceReference1", global::System.StringComparison.Ordinal))
            {
                return string.Concat("TheOldWebAPIService.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Racers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Racer> Racers
        {
            get
            {
                if ((this._Racers == null))
                {
                    this._Racers = base.CreateQuery<Racer>("Racers");
                }
                return this._Racers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Racer> _Racers;
        /// <summary>
        /// There are no comments for RaceResults in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RaceResult> RaceResults
        {
            get
            {
                if ((this._RaceResults == null))
                {
                    this._RaceResults = base.CreateQuery<RaceResult>("RaceResults");
                }
                return this._RaceResults;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RaceResult> _RaceResults;
        /// <summary>
        /// There are no comments for Racers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRacers(Racer racer)
        {
            base.AddObject("Racers", racer);
        }
        /// <summary>
        /// There are no comments for RaceResults in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRaceResults(RaceResult raceResult)
        {
            base.AddObject("RaceResults", raceResult);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"TheOldWebAPIService.Models\" xmlns=\"http://schemas.microsoft.com/ado/2" +
                "009/11/edm\"><EntityType Name=\"Racer\"><Key><PropertyRef Name=\"Id\" /></Key><Proper" +
                "ty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"FirstName\" Type" +
                "=\"Edm.String\" Nullable=\"false\" /><Property Name=\"LastName\" Type=\"Edm.String\" Nul" +
                "lable=\"false\" /><Property Name=\"Nationality\" Type=\"Edm.String\" /><Property Name=" +
                "\"Starts\" Type=\"Edm.Int32\" /><Property Name=\"Wins\" Type=\"Edm.Int32\" /><Property N" +
                "ame=\"Points\" Type=\"Edm.Int32\" /><Property Name=\"DateOfBirth\" Type=\"Edm.DateTime\"" +
                " /><Property Name=\"DateOfDeath\" Type=\"Edm.DateTime\" /><NavigationProperty Name=\"" +
                "RaceResults\" Relationship=\"TheOldWebAPIService.Models.TheOldWebAPIService_Models" +
                "_Racer_RaceResults_TheOldWebAPIService_Models_RaceResult_RaceResultsPartner\" ToR" +
                "ole=\"RaceResults\" FromRole=\"RaceResultsPartner\" /></EntityType><EntityType Name=" +
                "\"RaceResult\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.I" +
                "nt32\" Nullable=\"false\" /><Property Name=\"RaceId\" Type=\"Edm.Int32\" Nullable=\"fals" +
                "e\" /><Property Name=\"RacerId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name" +
                "=\"TeamId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Position\" Type=\"Ed" +
                "m.Int32\" Nullable=\"false\" /><Property Name=\"Number\" Type=\"Edm.Int32\" /><Property" +
                " Name=\"Grid\" Type=\"Edm.Int32\" /><Property Name=\"Points\" Type=\"Edm.Decimal\" /><Pr" +
                "operty Name=\"Time\" Type=\"Edm.Time\" /><Property Name=\"Laps\" Type=\"Edm.Int32\" /><P" +
                "roperty Name=\"Retired\" Type=\"Edm.String\" /><NavigationProperty Name=\"Race\" Relat" +
                "ionship=\"TheOldWebAPIService.Models.TheOldWebAPIService_Models_RaceResult_Race_T" +
                "heOldWebAPIService_Models_Race_RacePartner\" ToRole=\"Race\" FromRole=\"RacePartner\"" +
                " /><NavigationProperty Name=\"Racer\" Relationship=\"TheOldWebAPIService.Models.The" +
                "OldWebAPIService_Models_RaceResult_Racer_TheOldWebAPIService_Models_Racer_RacerP" +
                "artner\" ToRole=\"Racer\" FromRole=\"RacerPartner\" /></EntityType><EntityType Name=\"" +
                "Race\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" N" +
                "ullable=\"false\" /><Property Name=\"CircuitId\" Type=\"Edm.Int32\" Nullable=\"false\" /" +
                "><Property Name=\"Date\" Type=\"Edm.DateTime\" Nullable=\"false\" /><NavigationPropert" +
                "y Name=\"Circuit\" Relationship=\"TheOldWebAPIService.Models.TheOldWebAPIService_Mo" +
                "dels_Race_Circuit_TheOldWebAPIService_Models_Circuit_CircuitPartner\" ToRole=\"Cir" +
                "cuit\" FromRole=\"CircuitPartner\" /><NavigationProperty Name=\"RaceResults\" Relatio" +
                "nship=\"TheOldWebAPIService.Models.TheOldWebAPIService_Models_Race_RaceResults_Th" +
                "eOldWebAPIService_Models_RaceResult_RaceResultsPartner\" ToRole=\"RaceResults\" Fro" +
                "mRole=\"RaceResultsPartner\" /></EntityType><EntityType Name=\"Circuit\"><Key><Prope" +
                "rtyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /" +
                "><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"Coun" +
                "try\" Type=\"Edm.String\" Nullable=\"false\" /><NavigationProperty Name=\"Races\" Relat" +
                "ionship=\"TheOldWebAPIService.Models.TheOldWebAPIService_Models_Circuit_Races_The" +
                "OldWebAPIService_Models_Race_RacesPartner\" ToRole=\"Races\" FromRole=\"RacesPartner" +
                "\" /></EntityType><Association Name=\"TheOldWebAPIService_Models_Racer_RaceResults" +
                "_TheOldWebAPIService_Models_RaceResult_RaceResultsPartner\"><End Type=\"TheOldWebA" +
                "PIService.Models.RaceResult\" Role=\"RaceResults\" Multiplicity=\"*\" /><End Type=\"Th" +
                "eOldWebAPIService.Models.Racer\" Role=\"RaceResultsPartner\" Multiplicity=\"0..1\" />" +
                "</Association><Association Name=\"TheOldWebAPIService_Models_RaceResult_Race_TheO" +
                "ldWebAPIService_Models_Race_RacePartner\"><End Type=\"TheOldWebAPIService.Models.R" +
                "ace\" Role=\"Race\" Multiplicity=\"0..1\" /><End Type=\"TheOldWebAPIService.Models.Rac" +
                "eResult\" Role=\"RacePartner\" Multiplicity=\"0..1\" /></Association><Association Nam" +
                "e=\"TheOldWebAPIService_Models_RaceResult_Racer_TheOldWebAPIService_Models_Racer_" +
                "RacerPartner\"><End Type=\"TheOldWebAPIService.Models.Racer\" Role=\"Racer\" Multipli" +
                "city=\"0..1\" /><End Type=\"TheOldWebAPIService.Models.RaceResult\" Role=\"RacerPartn" +
                "er\" Multiplicity=\"0..1\" /></Association><Association Name=\"TheOldWebAPIService_M" +
                "odels_Race_Circuit_TheOldWebAPIService_Models_Circuit_CircuitPartner\"><End Type=" +
                "\"TheOldWebAPIService.Models.Circuit\" Role=\"Circuit\" Multiplicity=\"0..1\" /><End T" +
                "ype=\"TheOldWebAPIService.Models.Race\" Role=\"CircuitPartner\" Multiplicity=\"0..1\" " +
                "/></Association><Association Name=\"TheOldWebAPIService_Models_Race_RaceResults_T" +
                "heOldWebAPIService_Models_RaceResult_RaceResultsPartner\"><End Type=\"TheOldWebAPI" +
                "Service.Models.RaceResult\" Role=\"RaceResults\" Multiplicity=\"*\" /><End Type=\"TheO" +
                "ldWebAPIService.Models.Race\" Role=\"RaceResultsPartner\" Multiplicity=\"0..1\" /></A" +
                "ssociation><Association Name=\"TheOldWebAPIService_Models_Circuit_Races_TheOldWeb" +
                "APIService_Models_Race_RacesPartner\"><End Type=\"TheOldWebAPIService.Models.Race\"" +
                " Role=\"Races\" Multiplicity=\"*\" /><End Type=\"TheOldWebAPIService.Models.Circuit\" " +
                "Role=\"RacesPartner\" Multiplicity=\"0..1\" /></Association></Schema><Schema Namespa" +
                "ce=\"Default\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityContain" +
                "er Name=\"Container\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Racers\" E" +
                "ntityType=\"TheOldWebAPIService.Models.Racer\" /><EntitySet Name=\"RaceResults\" Ent" +
                "ityType=\"TheOldWebAPIService.Models.RaceResult\" /><AssociationSet Name=\"TheOldWe" +
                "bAPIService_Models_Racer_RaceResults_TheOldWebAPIService_Models_RaceResult_RaceR" +
                "esultsPartnerSet\" Association=\"TheOldWebAPIService.Models.TheOldWebAPIService_Mo" +
                "dels_Racer_RaceResults_TheOldWebAPIService_Models_RaceResult_RaceResultsPartner\"" +
                "><End Role=\"RaceResultsPartner\" EntitySet=\"Racers\" /><End Role=\"RaceResults\" Ent" +
                "itySet=\"RaceResults\" /></AssociationSet><AssociationSet Name=\"TheOldWebAPIServic" +
                "e_Models_RaceResult_Racer_TheOldWebAPIService_Models_Racer_RacerPartnerSet\" Asso" +
                "ciation=\"TheOldWebAPIService.Models.TheOldWebAPIService_Models_RaceResult_Racer_" +
                "TheOldWebAPIService_Models_Racer_RacerPartner\"><End Role=\"RacerPartner\" EntitySe" +
                "t=\"RaceResults\" /><End Role=\"Racer\" EntitySet=\"Racers\" /></AssociationSet></Enti" +
                "tyContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for TheOldWebAPIService.Models.Racer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Racers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Racer : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Racer object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Racer CreateRacer(int ID, string firstName, string lastName)
        {
            Racer racer = new Racer();
            racer.Id = ID;
            racer.FirstName = firstName;
            racer.LastName = lastName;
            return racer;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Nationality in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nationality
        {
            get
            {
                return this._Nationality;
            }
            set
            {
                this.OnNationalityChanging(value);
                this._Nationality = value;
                this.OnNationalityChanged();
                this.OnPropertyChanged("Nationality");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nationality;
        partial void OnNationalityChanging(string value);
        partial void OnNationalityChanged();
        /// <summary>
        /// There are no comments for Property Starts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Starts
        {
            get
            {
                return this._Starts;
            }
            set
            {
                this.OnStartsChanging(value);
                this._Starts = value;
                this.OnStartsChanged();
                this.OnPropertyChanged("Starts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Starts;
        partial void OnStartsChanging(global::System.Nullable<int> value);
        partial void OnStartsChanged();
        /// <summary>
        /// There are no comments for Property Wins in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Wins
        {
            get
            {
                return this._Wins;
            }
            set
            {
                this.OnWinsChanging(value);
                this._Wins = value;
                this.OnWinsChanged();
                this.OnPropertyChanged("Wins");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Wins;
        partial void OnWinsChanging(global::System.Nullable<int> value);
        partial void OnWinsChanged();
        /// <summary>
        /// There are no comments for Property Points in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Points
        {
            get
            {
                return this._Points;
            }
            set
            {
                this.OnPointsChanging(value);
                this._Points = value;
                this.OnPointsChanged();
                this.OnPropertyChanged("Points");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Points;
        partial void OnPointsChanging(global::System.Nullable<int> value);
        partial void OnPointsChanged();
        /// <summary>
        /// There are no comments for Property DateOfBirth in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> DateOfBirth
        {
            get
            {
                return this._DateOfBirth;
            }
            set
            {
                this.OnDateOfBirthChanging(value);
                this._DateOfBirth = value;
                this.OnDateOfBirthChanged();
                this.OnPropertyChanged("DateOfBirth");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateOfBirthChanged();
        /// <summary>
        /// There are no comments for Property DateOfDeath in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> DateOfDeath
        {
            get
            {
                return this._DateOfDeath;
            }
            set
            {
                this.OnDateOfDeathChanging(value);
                this._DateOfDeath = value;
                this.OnDateOfDeathChanged();
                this.OnPropertyChanged("DateOfDeath");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _DateOfDeath;
        partial void OnDateOfDeathChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateOfDeathChanged();
        /// <summary>
        /// There are no comments for RaceResults in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RaceResult> RaceResults
        {
            get
            {
                return this._RaceResults;
            }
            set
            {
                this._RaceResults = value;
                this.OnPropertyChanged("RaceResults");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RaceResult> _RaceResults = new global::System.Data.Services.Client.DataServiceCollection<RaceResult>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for TheOldWebAPIService.Models.RaceResult in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("RaceResults")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RaceResult : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RaceResult object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="raceId">Initial value of RaceId.</param>
        /// <param name="racerId">Initial value of RacerId.</param>
        /// <param name="teamId">Initial value of TeamId.</param>
        /// <param name="position">Initial value of Position.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RaceResult CreateRaceResult(int ID, int raceId, int racerId, int teamId, int position)
        {
            RaceResult raceResult = new RaceResult();
            raceResult.Id = ID;
            raceResult.RaceId = raceId;
            raceResult.RacerId = racerId;
            raceResult.TeamId = teamId;
            raceResult.Position = position;
            return raceResult;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RaceId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int RaceId
        {
            get
            {
                return this._RaceId;
            }
            set
            {
                this.OnRaceIdChanging(value);
                this._RaceId = value;
                this.OnRaceIdChanged();
                this.OnPropertyChanged("RaceId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _RaceId;
        partial void OnRaceIdChanging(int value);
        partial void OnRaceIdChanged();
        /// <summary>
        /// There are no comments for Property RacerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int RacerId
        {
            get
            {
                return this._RacerId;
            }
            set
            {
                this.OnRacerIdChanging(value);
                this._RacerId = value;
                this.OnRacerIdChanged();
                this.OnPropertyChanged("RacerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _RacerId;
        partial void OnRacerIdChanging(int value);
        partial void OnRacerIdChanged();
        /// <summary>
        /// There are no comments for Property TeamId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TeamId
        {
            get
            {
                return this._TeamId;
            }
            set
            {
                this.OnTeamIdChanging(value);
                this._TeamId = value;
                this.OnTeamIdChanged();
                this.OnPropertyChanged("TeamId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TeamId;
        partial void OnTeamIdChanging(int value);
        partial void OnTeamIdChanged();
        /// <summary>
        /// There are no comments for Property Position in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Position
        {
            get
            {
                return this._Position;
            }
            set
            {
                this.OnPositionChanging(value);
                this._Position = value;
                this.OnPositionChanged();
                this.OnPropertyChanged("Position");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Position;
        partial void OnPositionChanging(int value);
        partial void OnPositionChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Number;
        partial void OnNumberChanging(global::System.Nullable<int> value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property Grid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Grid
        {
            get
            {
                return this._Grid;
            }
            set
            {
                this.OnGridChanging(value);
                this._Grid = value;
                this.OnGridChanged();
                this.OnPropertyChanged("Grid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Grid;
        partial void OnGridChanging(global::System.Nullable<int> value);
        partial void OnGridChanged();
        /// <summary>
        /// There are no comments for Property Points in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Points
        {
            get
            {
                return this._Points;
            }
            set
            {
                this.OnPointsChanging(value);
                this._Points = value;
                this.OnPointsChanged();
                this.OnPropertyChanged("Points");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Points;
        partial void OnPointsChanging(global::System.Nullable<decimal> value);
        partial void OnPointsChanged();
        /// <summary>
        /// There are no comments for Property Time in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.TimeSpan> Time
        {
            get
            {
                return this._Time;
            }
            set
            {
                this.OnTimeChanging(value);
                this._Time = value;
                this.OnTimeChanged();
                this.OnPropertyChanged("Time");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.TimeSpan> _Time;
        partial void OnTimeChanging(global::System.Nullable<global::System.TimeSpan> value);
        partial void OnTimeChanged();
        /// <summary>
        /// There are no comments for Property Laps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Laps
        {
            get
            {
                return this._Laps;
            }
            set
            {
                this.OnLapsChanging(value);
                this._Laps = value;
                this.OnLapsChanged();
                this.OnPropertyChanged("Laps");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Laps;
        partial void OnLapsChanging(global::System.Nullable<int> value);
        partial void OnLapsChanged();
        /// <summary>
        /// There are no comments for Property Retired in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Retired
        {
            get
            {
                return this._Retired;
            }
            set
            {
                this.OnRetiredChanging(value);
                this._Retired = value;
                this.OnRetiredChanged();
                this.OnPropertyChanged("Retired");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Retired;
        partial void OnRetiredChanging(string value);
        partial void OnRetiredChanged();
        /// <summary>
        /// There are no comments for Race in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Race Race
        {
            get
            {
                return this._Race;
            }
            set
            {
                this._Race = value;
                this.OnPropertyChanged("Race");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Race _Race;
        /// <summary>
        /// There are no comments for Racer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Racer Racer
        {
            get
            {
                return this._Racer;
            }
            set
            {
                this._Racer = value;
                this.OnPropertyChanged("Racer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Racer _Racer;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for TheOldWebAPIService.Models.Race in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Race : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Race object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="circuitId">Initial value of CircuitId.</param>
        /// <param name="date">Initial value of Date.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Race CreateRace(int ID, int circuitId, global::System.DateTime date)
        {
            Race race = new Race();
            race.Id = ID;
            race.CircuitId = circuitId;
            race.Date = date;
            return race;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CircuitId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CircuitId
        {
            get
            {
                return this._CircuitId;
            }
            set
            {
                this.OnCircuitIdChanging(value);
                this._CircuitId = value;
                this.OnCircuitIdChanged();
                this.OnPropertyChanged("CircuitId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CircuitId;
        partial void OnCircuitIdChanging(int value);
        partial void OnCircuitIdChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Circuit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Circuit Circuit
        {
            get
            {
                return this._Circuit;
            }
            set
            {
                this._Circuit = value;
                this.OnPropertyChanged("Circuit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Circuit _Circuit;
        /// <summary>
        /// There are no comments for RaceResults in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RaceResult> RaceResults
        {
            get
            {
                return this._RaceResults;
            }
            set
            {
                this._RaceResults = value;
                this.OnPropertyChanged("RaceResults");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RaceResult> _RaceResults = new global::System.Data.Services.Client.DataServiceCollection<RaceResult>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for TheOldWebAPIService.Models.Circuit in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Circuit : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Circuit object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="country">Initial value of Country.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Circuit CreateCircuit(int ID, string name, string country)
        {
            Circuit circuit = new Circuit();
            circuit.Id = ID;
            circuit.Name = name;
            circuit.Country = country;
            return circuit;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
                this.OnPropertyChanged("Country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Races in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Race> Races
        {
            get
            {
                return this._Races;
            }
            set
            {
                this._Races = value;
                this.OnPropertyChanged("Races");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Race> _Races = new global::System.Data.Services.Client.DataServiceCollection<Race>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
